from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import threading

class TargetFinder(threading.Thread):
    def __init__(self):
        pass


driver = webdriver.Chrome()
driver.get('http://finance.yahoo.com/screener/new')

add_sector_button = driver.find_element_by_xpath("/html[@id='atomic']/body/div[@id='app']/div/div/div[@id='render-target-default']/main[@class='app']/div[@id='FIN-MainCanvas']/div[@class='Bxz(bb) H(100%) Pos(r) Maw($newGridWidth) Miw($minGridWidth) Miw(ini)!--tab768 Miw(ini)!--tab1024 Mstart(a) Mend(a) Px(20px) Z(3)']/div/div[@id='main-0-ScreenerDetail-Proxy']/section[@class='Pos(r)']/section[@class='Z(3) Va(t)']/section[@id='screener-criteria']/div[@class='Bd Bdc($grey4) W(100%) Bgc($panelBackground) Pt(14px) Pb(20px) Bdrs(3px) Pos(r) Mt(45px) Bdrststart(0px)!']/div[@class='Mstart(28px) Pend(25px)']/div/div[@class='D(ib) Fl(start)']/div[@class='Mb(5px) C($finDarkGray)'][4]/div[@class='D(ib) Bgc(white) Bdrs(3px)']/div[@class='D(ib) Bgc(white) Bdrs(3px) Pt(12px) Pb(9px) Pstart(18px) Pend(20px) Px(10px)--tab768 Mih(30px) Pos(r)'][1]/div[@class='D(ib) W(560px)--scrm W(510px)--scrl W(428px)!--tab768']/ul[@class='M(0) P(0) D(ib)']/li[@class='D(ib) Mb(3px) filterAdd']/div[@class='M(0) O(n):f D(ib) Bdrs(3px) Bgc($pillBgBlue):h C($finDarkGray) Fz(s)']/div[@class='D(ib) O(n):f Pt(6px) Pb(7px) Pstart(6px) Pend(7px) Bgc($extraLightBlue):f Cur(p)']/span[@class='Va(m) Mstart(6px) Mend(4px)']/span/span")
add_sector_button.click()

technology_checkbox = driver.find_element_by_xpath("/html[@id='atomic']/body/div[@id='app']/div/div/div[@id='render-target-default']/main[@class='app']/div[@id='FIN-MainCanvas']/div[@class='Bxz(bb) H(100%) Pos(r) Maw($newGridWidth) Miw($minGridWidth) Miw(ini)!--tab768 Miw(ini)!--tab1024 Mstart(a) Mend(a) Px(20px) Z(3)']/div/div[@id='main-0-ScreenerDetail-Proxy']/section[@class='Pos(r)']/section[@class='Z(3) Va(t)']/section[@id='screener-criteria']/div[@class='Bd Bdc($grey4) W(100%) Bgc($panelBackground) Pt(14px) Pb(20px) Bdrs(3px) Pos(r) Mt(45px) Bdrststart(0px)!']/div[@class='Mstart(28px) Pend(25px)']/div/div[@class='D(ib) Fl(start)']/div[@class='Mb(5px) C($finDarkGray)'][4]/div[@class='D(ib) Bgc(white) Bdrs(3px)']/div[@class='D(ib) Bgc(white) Bdrs(3px) Pt(12px) Pb(9px) Pstart(18px) Pend(20px) Px(10px)--tab768 Mih(30px) Pos(r)'][1]/div[@class='D(ib) W(560px)--scrm W(510px)--scrl W(428px)!--tab768']/ul[@class='M(0) P(0) D(ib)']/li[@class='D(ib) Mb(3px) filterAdd']/div[@class='M(0) O(n):f D(ib) Bdrs(3px) Bgc($pillBgBlue):h C($finDarkGray) Fz(s)']/div[@class='D(ib) O(n):f Pt(6px) Pb(7px) Pstart(6px) Pend(7px) Bgc($extraLightBlue):f']/div[@id='dropdown-menu']/div[@class='Py(15px)']/div[@class='Pstart(16px) Pend(20px) Mah(230px) Ovy(a)']/ul[@class='M(0) P(0)']/li[@class='Fl(start) D(b) Mb(10px)'][8]/label[@class='Ta(c) Pos(r) Va(tb) Pend(10px)']")
technology_checkbox.click()

sector_close_button = driver.find_element_by_xpath("/html[@id='atomic']/body/div[@id='app']/div/div/div[@id='render-target-default']/main[@class='app']/div[@id='FIN-MainCanvas']/div[@class='Bxz(bb) H(100%) Pos(r) Maw($newGridWidth) Miw($minGridWidth) Miw(ini)!--tab768 Miw(ini)!--tab1024 Mstart(a) Mend(a) Px(20px) Z(3)']/div/div[@id='main-0-ScreenerDetail-Proxy']/section[@class='Pos(r)']/section[@class='Z(3) Va(t)']/section[@id='screener-criteria']/div[@class='Bd Bdc($grey4) W(100%) Bgc($panelBackground) Pt(14px) Pb(20px) Bdrs(3px) Pos(r) Mt(45px) Bdrststart(0px)!']/div[@class='Mstart(28px) Pend(25px)']/div/div[@class='D(ib) Fl(start)']/div[@class='Mb(5px) C($finDarkGray)'][4]/div[@class='D(ib) Bgc(white) Bdrs(3px)']/div[@class='D(ib) Bgc(white) Bdrs(3px) Pt(12px) Pb(9px) Pstart(18px) Pend(20px) Px(10px)--tab768 Mih(30px) Pos(r)'][1]/div[@class='D(ib) W(560px)--scrm W(510px)--scrl W(428px)!--tab768']/ul[@class='M(0) P(0) D(ib)']/li[@class='D(ib) Mb(3px) filterAdd']/div[@class='M(0) O(n):f D(ib) Bdrs(3px) Bgc($pillBgBlue):h C($finDarkGray) Fz(s)']/div[@class='D(ib) O(n):f Pt(6px) Pb(7px) Pstart(6px) Pend(7px) Bgc($extraLightBlue):f']/div[@id='dropdown-menu']/button[@class='Bd(0) P(0) O(n):f D(ib) Fz(s) Fl(end) Mt(6px) Mend(8px) close']")
sector_close_button.click()

element_present = EC.presence_of_element_located((By.XPATH, "/html[@id='atomic']/body/div[@id='app']/div/div/div[@id='render-target-default']/main[@class='app']/div[@id='FIN-MainCanvas']/div[@class='Bxz(bb) H(100%) Pos(r) Maw($newGridWidth) Miw($minGridWidth) Miw(ini)!--tab768 Miw(ini)!--tab1024 Mstart(a) Mend(a) Px(20px) Z(3)']/div/div[@id='main-0-ScreenerDetail-Proxy']/section[@class='Pos(r)']/section[@class='Z(3) Va(t)']/section[@id='screener-criteria']/div[@class='Bd Bdc($grey4) W(100%) Bgc($panelBackground) Pt(14px) Pb(20px) Bdrs(3px) Pos(r) Mt(45px) Bdrststart(0px)!']/div[@class='Mstart(28px) Pend(25px)']/div/div[@class='D(ib) Fl(start)']/div[@class='Mb(5px) C($finDarkGray)'][4]/div[@class='D(ib) Bgc(white) Bdrs(3px)']/div[@class='D(ib) Bgc(white) Bdrs(3px) Pt(12px) Pb(9px) Pstart(18px) Pend(20px) Px(10px)--tab768 Mih(30px) Pos(r)'][2]/div[@class='D(ib) W(560px)--scrm W(510px)--scrl W(428px)!--tab768']/ul[@class='M(0) P(0) D(ib)']/li[@class='D(ib) Mb(3px) filterAdd']/div[@class='M(0) O(n):f D(ib) Bdrs(3px) Bgc($pillBgBlue):h C($finDarkGray) Fz(s)']/div[@class='D(ib) O(n):f Pt(6px) Pb(7px) Pstart(6px) Pend(7px) Bgc($extraLightBlue):f Cur(p)']"))
WebDriverWait(driver, 30).until(element_present)

add_industry_button = driver.find_element_by_xpath("/html[@id='atomic']/body/div[@id='app']/div/div/div[@id='render-target-default']/main[@class='app']/div[@id='FIN-MainCanvas']/div[@class='Bxz(bb) H(100%) Pos(r) Maw($newGridWidth) Miw($minGridWidth) Miw(ini)!--tab768 Miw(ini)!--tab1024 Mstart(a) Mend(a) Px(20px) Z(3)']/div/div[@id='main-0-ScreenerDetail-Proxy']/section[@class='Pos(r)']/section[@class='Z(3) Va(t)']/section[@id='screener-criteria']/div[@class='Bd Bdc($grey4) W(100%) Bgc($panelBackground) Pt(14px) Pb(20px) Bdrs(3px) Pos(r) Mt(45px) Bdrststart(0px)!']/div[@class='Mstart(28px) Pend(25px)']/div/div[@class='D(ib) Fl(start)']/div[@class='Mb(5px) C($finDarkGray)'][4]/div[@class='D(ib) Bgc(white) Bdrs(3px)']/div[@class='D(ib) Bgc(white) Bdrs(3px) Pt(12px) Pb(9px) Pstart(18px) Pend(20px) Px(10px)--tab768 Mih(30px) Pos(r)'][2]/div[@class='D(ib) W(560px)--scrm W(510px)--scrl W(428px)!--tab768']/ul[@class='M(0) P(0) D(ib)']/li[@class='D(ib) Mb(3px) filterAdd']/div[@class='M(0) O(n):f D(ib) Bdrs(3px) Bgc($pillBgBlue):h C($finDarkGray) Fz(s)']/div[@class='D(ib) O(n):f Pt(6px) Pb(7px) Pstart(6px) Pend(7px) Bgc($extraLightBlue):f Cur(p)']")
add_industry_button.click()

semicondutor_industry = driver.find_element_by_xpath("/html[@id='atomic']/body/div[@id='app']/div/div/div[@id='render-target-default']/main[@class='app']/div[@id='FIN-MainCanvas']/div[@class='Bxz(bb) H(100%) Pos(r) Maw($newGridWidth) Miw($minGridWidth) Miw(ini)!--tab768 Miw(ini)!--tab1024 Mstart(a) Mend(a) Px(20px) Z(3)']/div/div[@id='main-0-ScreenerDetail-Proxy']/section[@class='Pos(r)']/section[@class='Z(3) Va(t)']/section[@id='screener-criteria']/div[@class='Bd Bdc($grey4) W(100%) Bgc($panelBackground) Pt(14px) Pb(20px) Bdrs(3px) Pos(r) Mt(45px) Bdrststart(0px)!']/div[@class='Mstart(28px) Pend(25px)']/div/div[@class='D(ib) Fl(start)']/div[@class='Mb(5px) C($finDarkGray)'][4]/div[@class='D(ib) Bgc(white) Bdrs(3px)']/div[@class='D(ib) Bgc(white) Bdrs(3px) Pt(12px) Pb(9px) Pstart(18px) Pend(20px) Px(10px)--tab768 Mih(30px) Pos(r)'][2]/div[@class='D(ib) W(560px)--scrm W(510px)--scrl W(428px)!--tab768']/ul[@class='M(0) P(0) D(ib)']/li[@class='D(ib) Mb(3px) filterAdd']/div[@class='M(0) O(n):f D(ib) Bdrs(3px) Bgc($pillBgBlue):h C($finDarkGray) Fz(s)']/div[@class='D(ib) O(n):f Pt(6px) Pb(7px) Pstart(6px) Pend(7px) Bgc($extraLightBlue):f']/div[@id='dropdown-menu']/div[@class='Py(15px)']/div[@class='Pstart(16px) Pend(20px) Mah(230px) Ovy(a)']/ul[@class='M(0) P(0)']/li[@class='Fl(start) D(b) Mb(10px)'][15]/label[@class='Ta(c) Pos(r) Va(tb) Pend(10px)']")
semicondutor_industry.click()

semicondutor_industry = driver.find_element_by_xpath("/html[@id='atomic']/body/div[@id='app']/div/div/div[@id='render-target-default']/main[@class='app']/div[@id='FIN-MainCanvas']/div[@class='Bxz(bb) H(100%) Pos(r) Maw($newGridWidth) Miw($minGridWidth) Miw(ini)!--tab768 Miw(ini)!--tab1024 Mstart(a) Mend(a) Px(20px) Z(3)']/div/div[@id='main-0-ScreenerDetail-Proxy']/section[@class='Pos(r)']/section[@class='Z(3) Va(t)']/section[@id='screener-criteria']/div[@class='Bd Bdc($grey4) W(100%) Bgc($panelBackground) Pt(14px) Pb(20px) Bdrs(3px) Pos(r) Mt(45px) Bdrststart(0px)!']/div[@class='Mstart(28px) Pend(25px)']/div/div[@class='D(ib) Fl(start)']/div[@class='Mb(5px) C($finDarkGray)'][4]/div[@class='D(ib) Bgc(white) Bdrs(3px)']/div[@class='D(ib) Bgc(white) Bdrs(3px) Pt(12px) Pb(9px) Pstart(18px) Pend(20px) Px(10px)--tab768 Mih(30px) Pos(r)'][2]/div[@class='D(ib) W(560px)--scrm W(510px)--scrl W(428px)!--tab768']/ul[@class='M(0) P(0) D(ib)']/li[@class='D(ib) Mb(3px) filterAdd']/div[@class='M(0) O(n):f D(ib) Bdrs(3px) Bgc($pillBgBlue):h C($finDarkGray) Fz(s)']/div[@class='D(ib) O(n):f Pt(6px) Pb(7px) Pstart(6px) Pend(7px) Bgc($extraLightBlue):f']/div[@id='dropdown-menu']/div[@class='Py(15px)']/div[@class='Pstart(16px) Pend(20px) Mah(230px) Ovy(a)']/ul[@class='M(0) P(0)']/li[@class='Fl(start) D(b) Mb(10px)'][17]/label[@class='Ta(c) Pos(r) Va(tb) Pend(10px)']")
semicondutor_industry.click()
